### ISSUE TITLE
Can't re-start machines

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1483]
**Detailed description**
Can't re-start machines.

**Steps to reproduce**
- Create new machine
- Stop it from the end user portal
- Try to start it again from the end user portal or the admin portal.

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/38027565-57c176be-3290-11e8-9d4f-89ed42515ea8.png)

- environment version:
```
JumpScale
Core: branch: master (f316dcf) 15/03/2018, 11:06:22
Portal: branch: master (65f9ce5) 18/03/2018, 13:27:20
OpenvCloud
Core: branch: master (b99652a) 18/03/2018, 15:51:07
G8VDC: branch: master (b085672) 16/03/2018, 17:09:29
Selfhealing: branch: master (20ee0fa) 15/03/2018, 11:08:04
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```

**Comment by grimpy** [comment]
Fixed in #1487

**Comment by ahmedelsayed-93** [comment]
issue still exists 
![image](https://user-images.githubusercontent.com/24386820/38193781-1a9ddc0e-3674-11e8-91e6-a39089518901.png)

### software version
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (37922d2) 3/19/2018, 12:56:12 PM
OpenvCloud
Core: branch: master (386afad) 4/2/2018, 10:56:41 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (20ee0fa) 3/15/2018, 11:08:04 AM
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
